title: "Pedro Modolo"
email: "modolo.ph@gmail.com"
description: "Personal academic and research website"
url: "https://pedrohpmodolo.github.io"
github_username: "pedrohpmodolo"

# Navigation Menu
header_pages:
  - about.md
  - research.md
  - projects.md
  - cv.md
  - contact.md

# Theme and Custom Styling
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

minima:
  skin: auto
  include_custom_css: true
